### ISSUE TITLE
Ability to just show the ROMs loaded (not the entire list)

### ISSUE THREAD

**Issue by yogi1967** [lesbird/MAME4apple-037b5#7] opened 2016-11-02 16:03 UTC
Perhaps not quite a bug, but the app is almost unusable when you have to slowly scroll through the 2000 potential game titles to find the exact one you have loaded and want to play. Impossible if you are not quite sure which one in a set it is. Please can there be a simple filter to only show on the game select menu the game roms actually loaded? Thanks

**Comment by lesbird** [comment] 2016-11-03 00:27
Hi, so you'd like the app to cross reference all the game titles with the roms you copied to your device? Yes, that should be possible. I will try to get that in by this weekend. Thanks for the suggestion.

**Comment by yogi1967** [comment] 2016-11-03 09:23
Hi, yes. So if I've only loaded 5 roms , I only want to see those 5 listed. Thanks.

**Comment by lesbird** [comment] 2016-11-06 19:03
Just updated the project to show only games with valid ROMs installed.

**Comment by iostriz** [comment] 2016-11-07 18:03
It does not work for me - (I'm using iPad for now).
I have found that the problem is at line 470 in file GameScene.m.
Currently, it looks like:

``` objective-c
NSString *path = [NSString stringWithUTF8String:getROMpath()];
[path stringByAppendingPathComponent:[NSString stringWithUTF8String:gameDriverList[i].gameDriver->name]];
```

The problem is that `stringByAppendingPathComponent` does not modify `path`, it returns a new string (NSString is immutable).
It should be something like:

``` objective-c
NSString *path = [NSString stringWithUTF8String:getROMpath()];
path = [path stringByAppendingPathComponent:[NSString stringWithUTF8String:gameDriverList[i].gameDriver->name]];
path = [path stringByAppendingPathExtension:@"zip"];
```

Also, I have added "zip" extension, because I'm using zip ROMs, I don't know the variety of formats they can come...

**Comment by lesbird** [comment] 2016-11-08 00:12
Oh wow, I wonder how that happened. Haha. Obviously I was pretty distracted when I wrote that because you're right, no way that would work.

**Comment by orff** [comment] 2016-11-08 20:58
Latest version shows a filtered list for me ( iOS version ).

**Comment by iostriz** [comment] 2016-11-09 16:56
You can close it now, I guess...

**Closed as completed** 2016-11-10 01:03 UTC
